name: "setup"
description: "Enable corepack, install dependencies"

runs:
  using: "composite"

  steps:
      - name: Corepack enable
        shell: bash
        run: |
          npm i -g corepack@latest
          corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile --prefer-offline

