# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy package manifest files
COPY package.json pnpm-lock.yaml ./

# Install dependencies (ignore scripts since build runs separately)
RUN pnpm install --frozen-lockfile --ignore-scripts

# Copy rest of the source code
COPY . .

# Build the project
RUN pnpm run build

# Expose a port if needed (not specified, but often MCP servers use stdio)

# Command to run the MCP server
CMD ["node", "dist/index.js"]
